### ISSUE TITLE
Test L2 Norm

### ISSUE THREAD

**Issue by blumenstiel** [blumenstiel/TDT4265-project#11]

**Comment by blumenstiel** [comment]
@HaukeTh @marianasonja  Testen wir L2 noch oder lassen wir es, da es mit Bachnorm und LR Scheduler eigentlich kein Effekt mehr hat?

**Comment by HaukeTh** [comment]
Würde es weglassen denke ich. Können ja auch nicht mehr allzu viele Modelle testen...
