### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by blumenstiel** [blumenstiel/TDT4265-project#3]

**Comment by marianasonja** [comment]
Ideas for Data Augmentation:

Use: 
**from preprocessing import tf_image**

- [x] Resize image (from 300x300 to 600x600) to detect smaller attributes/boxes too 

- [x] Rotation/Flipping
dst_image, bboxes = tf_image.random_flip_left_right(dst_image, bboxes)

- [x] Random Brightness
image = tf.image.random_brightness(image, max_delta=32. / 255.)

- [x] Random Contrast
image = tf.image.random_contrast(image, lower=0.5, upper=1.5)

- [x] Randrom Cropping 

- [x] Random Saturation
 image = tf.image.random_saturation(image, lower=0.5, upper=1.5)

- [x] Random Hue
image = tf.image.random_hue(image, max_delta=0.2)

See [SSD VGG Preprocessing](https://github.com/balancap/SSD-Tensorflow/blob/master/preprocessing/ssd_vgg_preprocessing.py)

**Comment by blumenstiel** [comment]
Test on branch "first" with resnext

- [x] default
- [x] improved samples
- [ ] ColorJitter
