### ISSUE TITLE
Crop TDT4265 dataset to square images

### ISSUE THREAD

**Issue by HaukeTh** [blumenstiel/TDT4265-project#7]

**Comment by blumenstiel** [comment]
@HaukeTh Wie hast du es auf dem Kurs Datenset aktuell laufen? Sollen wir da auch nochmal etwas ausprobieren?

**Comment by HaukeTh** [comment]
@blumenstiel Habs bisher ignoriert... Sollten wir uns aber definitiv noch angucken
